"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cylinderVolume = exports.coneVolume = exports.sphereVolume = exports.cuboidVolume = exports.cubeVolume = exports.cylinderArea = exports.coneArea = exports.sphereArea = exports.cuboidArea = exports.cubeArea = exports.rhombusArea = exports.parallelogramArea = exports.triangleArea = exports.circleArea = exports.rectangleArea = exports.squareArea = void 0;
var area2d_1 = require("./functions/area2d");
Object.defineProperty(exports, "squareArea", { enumerable: true, get: function () { return area2d_1.squareArea; } });
Object.defineProperty(exports, "rectangleArea", { enumerable: true, get: function () { return area2d_1.rectangleArea; } });
Object.defineProperty(exports, "circleArea", { enumerable: true, get: function () { return area2d_1.circleArea; } });
Object.defineProperty(exports, "triangleArea", { enumerable: true, get: function () { return area2d_1.triangleArea; } });
Object.defineProperty(exports, "parallelogramArea", { enumerable: true, get: function () { return area2d_1.parallelogramArea; } });
Object.defineProperty(exports, "rhombusArea", { enumerable: true, get: function () { return area2d_1.rhombusArea; } });
var area3d_1 = require("./functions/area3d");
Object.defineProperty(exports, "cubeArea", { enumerable: true, get: function () { return area3d_1.cubeArea; } });
Object.defineProperty(exports, "cuboidArea", { enumerable: true, get: function () { return area3d_1.cuboidArea; } });
Object.defineProperty(exports, "sphereArea", { enumerable: true, get: function () { return area3d_1.sphereArea; } });
Object.defineProperty(exports, "coneArea", { enumerable: true, get: function () { return area3d_1.coneArea; } });
Object.defineProperty(exports, "cylinderArea", { enumerable: true, get: function () { return area3d_1.cylinderArea; } });
var volume3d_1 = require("./functions/volume3d");
Object.defineProperty(exports, "cubeVolume", { enumerable: true, get: function () { return volume3d_1.cubeVolume; } });
Object.defineProperty(exports, "cuboidVolume", { enumerable: true, get: function () { return volume3d_1.cuboidVolume; } });
Object.defineProperty(exports, "sphereVolume", { enumerable: true, get: function () { return volume3d_1.sphereVolume; } });
Object.defineProperty(exports, "coneVolume", { enumerable: true, get: function () { return volume3d_1.coneVolume; } });
Object.defineProperty(exports, "cylinderVolume", { enumerable: true, get: function () { return volume3d_1.cylinderVolume; } });
